language: node_js
node_js:
  - "14" 
cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Lint, Test, Build
      name: Lint
      script:
        - cd App
        - npm install
        - npm run lint
    - name: Test
      script:
        - cd App
        - npm install
        - npm test -- --coverage
    - name: Build
      script:
        - cd App
        - npm install
        - npm run build

# safelist
branches:
  only:
  - main
  - unit-tests